name: pia
channels:
  - defaults
dependencies:
  - python=3.9
  - notebook
  - seaborn
  - tqdm
  - ipywidgets
  - numpy
  - pandas
  - pip
  - numpy<1.23
  - scikit-learn
  - pip:
      - hydra-core
